### ISSUE TITLE
Dockerization of local environment

### ISSUE THREAD

**Issue by JMyrtue** [aau-giraf/web-api#329]
## Description
Define a Docker Compose file for local development.
Replaces #192. 

**Possible Suggested Solution**  
- The Docker Compose file should initiate the web-api, and the MySQL server, and connect these.

**Definition of Done**
- When a Docker compose file can be called to instantiate a container with a MySQL server and the GIRAF web-api.
- The underlying Dockerfiles must correctly define the MySQL server and GIRAF web-api.
- Manually test that the endpoints are reachable through the container.

**Comment by JMyrtue** [comment]
Completed, but missing functionality from #327 before it is usable.

Will be merged with the above mentioned issue.

**Comment by KristianS93** [comment]
In regards of using the sample data, if we in the dockerfile specify that we will run the application with "--sample-data" instead of "--list" to show the options, we will trigger the running of the sample data.
I have tested that if data already exist it will not override the inserted data.

This brings us to the migration, in order for this to work, we have to create a clause that when the program is run with the LocalDocker environment variable we do a check if the database is connected and then we use the context.Database.Migration. function.
